### ISSUE TITLE
Expose ability to set classes on the DirectionProvider div

### ISSUE THREAD

**Issue by ronanmulvaney** [airbnb/react-with-direction#10]
Hi,

Great tool first, no issues here but we have a requirement to apply a class to the div and was wondering if you might expose the ability to set this through the DirectionProvider.

Thanks.

**Comment by ljharb** [comment]
That wouldn't be appropriate; https://brigade.engineering/don-t-pass-css-classes-between-components-e9f7ab192785

You may want to wrap it in an additional div with a className on it?
