### ISSUE TITLE
npm install - removes other modules

### ISSUE THREAD

**Issue by Mulli** [airbnb/react-with-direction#11]
Please provide installation guidelines.
Currently npm install react-with-direction breaks my project.
What am I missing?

**Comment by ljharb** [comment]
I think you’re probably experiencing an issue with npm itself; are all you installed dependencies listed in package.json? In npm 5, npm install will remove anything not in your package.json.

**Comment by Mulli** [comment]
Can you please provide installation guidelines - when adding to an existing react project?
I am new to npm,webpack,node, react etc...
Thanks!

**Comment by ljharb** [comment]
Same as any other JavaScript project - `npm install --save new-thing` or `npm install --save-dev new-thing`.
