### ISSUE TITLE
Jest tests failing without module mock

### ISSUE THREAD

**Issue by dac09** [airbnb/react-with-direction#13]
Hi,

Jest tests fail on my project created with create-react-app.

One of the errors I get is: 
```
 TypeError: Cannot read property 'propTypes' of undefined

      at withDirection (node_modules/react-with-direction/dist/withDirection.js:131:24)
```
This is very likely related to the provider (and the fact that tests don't have them). Other tests fail, but don't produce warnings realted to direction (although that is the cause).

For now I've mocked the react-with-direction module:

**src/__mocks__/react-with-direction.js**
```
let reactWithDirection = jest.genMockFromModule('react-with-direction');

reactWithDirection = {
  ...reactWithDirection,
  default: component => component
};

module.exports = reactWithDirection;
```

This seems to resolve it.

Is there a recommended solution for this?

Thanks!

**Comment by ljharb** [comment]
I'm confused, what do you mean "the fact that the tests don't have them"?

**Comment by ljharb** [comment]
If you're using `withDirection`, then `DirectionProvider` is required - so your tests also need to have them, otherwise they're not correct tests.

**Comment by dac09** [comment]
I'll give you an example of the tests that fail:

```
  it('Should remember state if its passed in', () => {
    const wrapper = mount(
      <MyComponent
        onSubmit={mockSubmit}
      />
    );

    expect(wrapper.state('answer')).toBe('option2');
  });
```

I understand that the Provider is required, but is the expectation in unit tests to write:
```
<DirectionProvider>
<ComponentToTest/>
</DirectionProvider>
```
?

Perhaps a utility function to provide context for tests would be helpful, e.g. for react-intl, a modified mount function can be used to provide context

```
function nodeWithIntlProp(node: ReactElement) {
  return React.cloneElement(node, { intl });
}

export function mountWithIntl(node: ReactElement) {
  return mount(nodeWithIntlProp(node), {
    context: { intl },
    childContextTypes: { intl: intlShape }
  });
}
```

**Comment by ljharb** [comment]
Yes, that's the requirement in unit tests, to include the DirectionProvider explicitly.

**Comment by dac09** [comment]
Ok, great. Thanks 👍

**Comment by yzimet** [comment]
A bit more explanation:

A component that is wrapped with `withDirection` will use direction context from the closest DirectionProvider. If DirectionProvider is not present anywhere in the tree, the withDirection HOC will use a [LTR direction context by default](https://github.com/airbnb/react-with-direction/blob/8c15a1b43b821b1eeab7cea25d50dfa0700cecf1/src/withDirection.jsx#L20-L22). So technically DirectionProvider is not required.

In your tests, if you are testing something unrelated to direction you can choose to not provide a DirectionProvider. For example:

```jsx
const wrapper = shallow(
  <ForwardsLabel
    onPress={onPress}
  />
).dive();

expect(wrapper.prop('foo')).to.equal('bar');
```

In this example I'm using Enzyme's [`dive`](http://airbnb.io/enzyme/docs/api/ShallowWrapper/dive.html) method to dive through the withDirection HOC.

**Comment by dac09** [comment]
Thanks @yzimet. That's very useful!
