### ISSUE TITLE
error in typescript project

### ISSUE THREAD

**Issue by yacsaeedi** [airbnb/react-with-direction#33]
error in typescript project 
Could not find a declaration file for module 'react-with-direction/dist/DirectionProvider'. 'D:/next project/gandom-front/node_modules/react-with-direction/dist/DirectionProvider.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-with-direction` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-with-direction/dist/DirectionProvider';`

**Comment by ljharb** [comment]
This is how most every package works; you need to install a DT package if one exists.

**Comment by yacsaeedi** [comment]
what is DT package?

**Comment by ljharb** [comment]
DefinitelyTyped. It’s where types for almost every npm package are defined.
